config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :join, only: [:index]
  resource :home, only: [:show]
  resources :mentors
  resources :mentees
  resources :app, only: :index
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'join/mentor', to: 'join#mentor', as: 'join_mentor'
  get 'join/mentee', to: 'join#mentee', as: 'join_mentee'
  # constraints(subdomain: 'app') do
  #   get '/', to: 'app#index', as: :app
  # end
  root 'home#show'
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # include ActionController::Live
  def show
  end
  # def stream
  #   response.headers['Content-Type'] = 'text/event-stream'
  #   100.times {
  #     response.stream.write "hello world\n"
  #     sleep 1
  #   }
  # ensure
  #   response.stream.close
  # end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/show.html.erb
<% content_for(:navbar) do %>
<ul id="nav-mobile" class="right hide-on-med-and-down">
  <!-- <li><a href="#">Links Would Look Like This</a></li> -->
  <% if current_user %>
  Signed in as
  <strong><%= current_user.email %></strong>!
  <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:'btn' %>
  <%= link_to "Edit Profile", edit_user_registration_path, class:'btn' %>
<% else %>
  <br>
  <a class='btn' style="cursor: pointer" onclick="javascript: window.location = '<%= user_github_omniauth_authorize_path %>';" data-disable-with="Some Magic is happening...">Continue With Github<i class="icon ion-social-github"></i>
  </a>
  <a class='btn' style="cursor: pointer" onclick="javascript: window.location = '<%= user_google_oauth2_omniauth_authorize_path %>';" data-disable-with="Some Magic is happening...">Continue With Google<i class="icon ion-social-google"></i>
  </a>
  <a class='btn' style="cursor: pointer" onclick="javascript: window.location = '<%= user_facebook_omniauth_authorize_path %>';" data-disable-with="Some Magic is happening...">Continue With Facebook<i class="icon ion-social-facebook"></i>
  </a>
  <a class='btn' style="cursor: pointer" onclick="javascript: window.location = '<%= new_user_registration_path %>';" data-disable-with="Some Magic is happening...">Prefer Good old Mail?<i class="icon ion-email"></i>
  </a>
  <% end %>
</ul>
<% end %>
<img class="responsive-img cover" src="<%= asset_path 'cover.jpg'%>">
<div class="white-text">
  <h2 class="mid typed"></h2>
  <% if user_signed_in? && current_user.complete %>
  <%= link_to 'Go To App', app_index_path, class:'btn btnm'%>
  <% elsif user_signed_in? %>
  <%= link_to 'Join The Revolution', join_index_path, class:'btn btnm'%>
  <% end %>
</div>