config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :join, only: [:index]
  resource :home, only: [:show]
  resources :mentors
  resources :mentees
  resources :app, only: :index
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'join/mentor', to: 'join#mentor', as: 'join_mentor'
  get 'join/mentee', to: 'join#mentee', as: 'join_mentee'
  # constraints(subdomain: 'app') do
  #   get '/', to: 'app#index', as: :app
  # end
  root 'home#show'
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/join_controller.rb
class JoinController < ApplicationController
  before_action :authenticate
  def index
  end

  def mentor
    @mentor = Mentor.new
  end

  def mentee
    @mentee = Mentee.new
  end

  private
  def authenticate
    redirect_to root_path, flash:{ alert:'Please Sign in First'}  if !user_signed_in?
    redirect_to app_index_path if current_user.complete
    # Use below when I can use subdomains
    # redirect_to app_url(subdomain: :app) if current_user.complete
  end
end

app/helpers/join_helper.rb
module JoinHelper
end

app/views/join/index.html.erb
<% content_for(:navbar) do %>
<ul id="nav-mobile" class="right hide-on-med-and-down">
  <!-- <li><a href="#">Links Would Look Like This</a></li> -->
  <% if current_user %>
  Signed in as
  <strong><%= current_user.email %></strong>!
  <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:'btn' %>
  <%= link_to "Edit Profile", edit_user_registration_path, class:'btn' %>
  <% end %>
</ul>
<% end %>
<img class="responsive-img cover" src="<%= asset_path 'cover.jpg'%>">
<div class="white-text decision">
  <%= link_to 'Become A Mentor', join_mentor_path, class:'btn left'%>
  <%= link_to 'Become A Mentee', join_mentee_path, class:'btn right'%>
</div>